name: filemanager
base: core24
version: '2.0.0'
title: FileManager
summary: Modern file manager with Rust+Go backend
description: |
  FileManager v2 is a major upgrade with improved performance and new features.
  Built with Rust and Go for cross-platform offering high performance and modern features for file management.
  
  New in v2:
  - Improved Rust FFI integration
  - Enhanced performance
  - Better file operation handling
  - Modern architecture

  Features:
  - Fast file operations with Rust backend
  - Intuitive user interface
  - Cross-platform compatibility
  - Advanced file search and filtering
  - Batch operations support

license: MIT
contact: moses.muranja@strathmore.edu
website: https://github.com/devonionrouting4Moses/fileManager
source-code: https://github.com/devonionrouting4Moses/fileManager
issues: https://github.com/devonionrouting4Moses/fileManager/issues
donation: https://github.com/sponsors/devonionrouting4Moses

grade: stable
confinement: strict
platforms:
  amd64:
  arm64:

apps:
  filemanager:
    command: usr/local/bin/filemanager
    environment:
      LD_LIBRARY_PATH: $SNAP/usr/local/lib:$LD_LIBRARY_PATH
      SNAP_REAL_HOME: $HOME
    plugs:
      - home
      - removable-media
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - wayland
      - x11
      - unity7

parts:
  rust-deps:
    plugin: nil
    build-packages:
      - curl
      - build-essential
    override-build: |
      # Install Rust
      curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
      . $HOME/.cargo/env
      rustc --version

  filemanager:
    after: [rust-deps]
    plugin: nil
    source: .
    build-packages:
      - golang-go
      - build-essential
      - pkg-config
      - libssl-dev
      - curl
      - wget
    stage-packages:
      - libc6
      - libgcc-s1
      - libstdc++6
    override-build: |
      set -e
      
      echo "Building FileManager for Snap..."
      
      # Setup Rust environment
      . $HOME/.cargo/env
      rustc --version
      
      # Build Rust library
      echo "Building Rust library..."
      cd rust_ffi
      cargo build --release -p fs-operations-core
      cd ..
      
      # Verify Rust library was built
      if [ ! -f rust_ffi/target/release/libfs_operations_core.so ]; then
        echo "ERROR: Rust library not found!"
        ls -la rust_ffi/target/release/ || echo "Release directory not found"
        exit 1
      fi
      echo "✅ Rust library built successfully"
      
      # Fix go.mod version if needed (snapcraft may have older Go)
      echo "Checking Go version compatibility..."
      GO_VERSION=$(go version | awk '{print $3}' | sed 's/go//')
      echo "Available Go version: $GO_VERSION"
      
      # Downgrade go.mod to compatible version if needed
      if [ -f file_manager/go.mod ]; then
        # Check if go.mod requires 1.24
        if grep -q "^go 1.24" file_manager/go.mod; then
          echo "Downgrading go.mod from 1.24 to 1.21 for compatibility..."
          sed -i 's/^go 1.24$/go 1.21/' file_manager/go.mod
        fi
      fi
      
      # Build Go binary
      echo "Building Go binary..."
      cd file_manager
      export CGO_ENABLED=1
      export CGO_LDFLAGS="-L../rust_ffi/target/release -lfs_operations_core -ldl -lpthread -lm"
      
      # Use go mod download with timeout to avoid issues
      timeout 300 go mod download || echo "⚠️  go mod download had issues, continuing..."
      
      go build -ldflags="-s -w" -o ../filemanager ./cmd/app
      cd ..
      
      if [ ! -f filemanager ]; then
        echo "ERROR: Go binary not found!"
        exit 1
      fi
      echo "✅ Go binary built successfully"
      
      # Install files
      install -D -m 755 filemanager ${SNAPCRAFT_PART_INSTALL}/usr/local/bin/filemanager
      
      # Install Rust library
      install -D -m 644 rust_ffi/target/release/libfs_operations_core.so ${SNAPCRAFT_PART_INSTALL}/usr/local/lib/libfs_operations_core.so
      
      # Install documentation
      if [ -f README.md ]; then
        install -D -m 644 README.md ${SNAPCRAFT_PART_INSTALL}/usr/share/doc/filemanager/README.md
      fi
      
      if [ -f LICENSE ]; then
        install -D -m 644 LICENSE ${SNAPCRAFT_PART_INSTALL}/usr/share/doc/filemanager/LICENSE
      fi
      
      echo "✅ Snap build completed successfully"

  desktop-file:
    plugin: dump
    source: snap/local/
    source-type: local
    organize:
      filemanager.desktop: usr/share/applications/filemanager.desktop
      filemanager.png: usr/share/icons/hicolor/256x256/apps/filemanager.png